//EN ESTA PRIMERA LINEA METE DENTRO DE UNA CONSTANTE (UNA CAJITA) 
//EL PAQUETE MONGOOSE QUE YA HEMOS INSTALADO ANTES CON NPM INSTALL MONGOOSE
//ESTO LO QUE HACE ES QUE A PARTIR DE AQUI CON LA PALABRA mongoose VAMOS A PODER USAR TODAS LAS
//UTILIDADES QUE TRAE EL PAQUETE
const mongoose = require('mongoose');

//EN ESTA LINEA USAMOS UNA DE LOS METODOS QUE TRAE MONGOOSE QUE ES EL .connect Y NOS CONECTAMOS
//A LA BASE DE DATOS ESPECIFICADA
mongoose.connect('mongodb://localhost/xtremecomics', {useNewUrlParser: true, useUnifiedTopology: true });

//Y AQUI LE DECIMOS QUE CUANDO LA CONEXION ESTE ABIERTA PUES NOS IMPRIMA EN CONSOLA CONECTADO
mongoose.connection.on('open', _=>{
    console.log('conectado')
}
);

//SI LO INICIAMOS EN CONSOLA CON node conexion.js O LA RUTA QUE CORRESPONDA EN ESTE CASO MIO
//node conexion.js
//PUES SE CONECTARA AL SERVIDOR DE LA BASE DE DATOS.j